# Example Secret - DO NOT commit actual secrets to git!
# Use sealed-secrets, external-secrets, or manual creation
apiVersion: v1
kind: Secret
metadata:
  name: aiq-secrets
type: Opaque
stringData:
  secret_key: "your-production-secret-key-here"
  database_url: "postgresql://user:pass@postgres-service:5432/aiq_db"
  model_service_url: "http://kserve-model.default.svc.cluster.local/v1/models/circular-detector" 